IF
  Clicked([PC])
  OpenState("Altar01",FALSE)
  Global("Altar_Open","GLOBAL",0)
THEN
  RESPONSE #100
    OpenDoor("Altar01")
    SetGlobal("Altar_Open","GLOBAL",1)
    TriggerActivation("Tran0308",TRUE)
END

IF
  Clicked([PC])
  OpenState("Altar01",TRUE)
  Global("Altar_Open","GLOBAL",1)
THEN
  RESPONSE #100
    CloseDoor("Altar01")
    SetGlobal("Altar_Open","GLOBAL",0)
    TriggerActivation("Tran0308",FALSE)
END

