IF
	Global("BHPelltarSpawn","BG3402",0)
	InMyArea(Player1)
	GlobalGT("Chapter","GLOBAL",2)
	GlobalLT("Chapter","GLOBAL",6)
THEN
	RESPONSE #100
		SetGlobal("BHPelltarSpawn","BG3402",1)
		CreateCreature("BHPell",[328.367],15) // Pelltar
END

IF
	OR(2)
		Global("BHQuestAccept","GLOBAL",8)
		GlobalGT("Chapter","GLOBAL",5)
	Exists("BHPell")
THEN
	RESPONSE #100
		ActionOverride("BHPell",DestroySelf())
		SetGlobal("BHQuestAccept","GLOBAL",9)
END